### ISSUE TITLE
Address null mappings for PV signals to rxnorm and snomed

### ISSUE THREAD

**Issue by rkboyce** [OHDSI/KnowledgeBase#58]
A few ATCs that do not exist in the Standard Vocab:
'D11AX17','C10AX04','D03AX08','A11CC07','G03DC05','D11AX15','N07BA02','D03AX07','D11AX14','N05AK01','L04AA05','N05CM17','L04AA01'

 
Some of these MedDRA codes in the CUI|MedDRA lookup (from UMLS) just go nowhere in the Standard Vocab.  For example, the top 10 most common CUIs that go nowhere aren’t really conditions.  

CUI                         MEDDRA              MEDDRA DESCRIPTION

C0919887             – 10051118 - Drug ineffective for unapproved indication

C0235874             – 10010264 - Condition aggravated

C0151905             – 10001551 - Alanine aminotransferase increased

C0151904             – 10003481 - Aspartate aminotransferase increased

C0235431             – 10005483 - Blood creatinine increased

C0877211             – 10049438 - General physical health deterioration

C0021311             – NOT IN LOOKUP

C1167981             – 10059923 - Pharyngeal hypoaesthesia

C2609418             – 20000156 - MEDDRA NOT IN VOCAB (Corneal disorders (SMQ))

C0852911             – 10059570 - Blood alkaline phosphatase increased

**Comment by cgreich** [comment]
Rich:

They are ugly as sin as outcomes. "Alanine aminotransferase increased" is not an outcome, it is a pathogenetic mechanism, or a symptom. I see two things we could do:

- Kick them out
- Map them by hand to something more useful (i.e. liver injury)

**Comment by ntatonetti** [comment]
Christian,

I both agree with you and disagree. I agree that in terms of general ADRs that we may want to define as outcomes “Alanine aminotransferase increased” may be more useful if mapped to a more general term. However, it is certainly an outcome and, in fact, much more expressive in terms of the molecular effect than something like “Liver Injury” which says nothing about the mechanism. 

I think that it is critical that we keep these types of outcomes in. Perhaps we can use a hierarchical terminology to map them to more general terms (e.g. Liver Injury) when needed, but they have great value as they are.

-N

**Comment by pbr6cornell** [comment]
I agree with Nick that we shouldn't 'kick out' adverse events associated
with 'ALT increase'.  The challenge becomes how to properly classify them.
If we map to SNOMED's concept of 'ALT abnormal', we've got two issues:  1)
the 'abnormal' doesn't tell you whether its increased or decreased, and
moreover, knowing someone had a increase doesn't mean it's abnormal,   and
2) this concept is a measurement, not a condition.    A viable SNOMED
concept in the 'condition' domain could be something like:  'Liver function
test abnormal', but that's neither specific nor necessarily accurate, but
it'd probably be better than rolling all the way up to something like
'liver injury'.

In any case, it seems that observations from a laboratory measurement
(either one point-in-time abnormal values,  or changes over time) represent
important characteristics that deserve some special attention for how to
manage, and it may be worth a discussion thread on the forums to explore
further.   I'd vote for a mapping to a condition concept as the starting
point, recognizing that we may change at some time in the future.  But to
Rich's original post, we can always leave source_values as is and map to 0
'unknown concept', so we don't 'lose' the data in the initial load.

Cheers,

Patrick

**Comment by cgreich** [comment]
Hang on, guys:

Why is "Alanine aminotransferase increased” (or "Liver function test abnormal" for that matter) different from "liver injury"? The reason the enzyme is in the blood stream is becasue hepatocytes die, and the content (those metabolic enzymes) get released. So, neither is better. Except sometimes you have more ALT and sometimes more AST, and that could be construed as an important pathological distinction. Which it isn't. but folks may argue that way.

I would argue we should go to the condition. Because we never capture the pathological mechanism or lab tests when talking about drug outcome: Vioxx causes heart attacks, not elevated troponin. The pathological mechanims for Vioxx isn't even known, some blame platelet stickiness for it. All outcomes people are studying (and OMOP studied) are conditions.

So, let's roll up to "Liver injury" (which is not to be confused with the fulminant idiosyncratic liver failure, which is another outcome).

**Comment by rkboyce** [comment]
TODO: test the concept similarity mappings and see what comes out - is it useful?
